### ISSUE TITLE
上传菜品图片，签名验证失败

### ISSUE THREAD

**Issue by chenhaizano** [HanSon/meituan-sdk#5]
### 文档
> ### 上传菜品图片
> #### 1. 功能说明
> 上传菜品图片到美团云，支持jpg，jpeg格式，上传成功会返回图片id，可以使用此id值批量上传菜品。 
> `注意: 此接口只有url后的queryString会计入签名, body里的数据不参与签名计算。`
> http://developer.meituan.com/openapi#7.2.10

文档说：此接口只有url后的queryString会计入签名, body里的数据不参与签名计算。

这里跟其他接口需要签名参数不一样，可能是造成签名失败的原因。

**Comment by Hanson** [comment]
这里的 body 并没有加入签名计算

```
$meituan->waimai->dish->uploadImage([
    'ePoiId' => 1,
    'imageName' => 'test.jpg',
], __DIR__.'/test.jpg')
```

这样签名错误？

**Comment by chenhaizano** [comment]
我就是这样调用，确实提示签名错误了。

你那边测试没问题么？

**Comment by Hanson** [comment]
@chenhaizano 解决了？

**Comment by chenhaizano** [comment]
@HanSon 不是上传图片的问题，是上传菜品时报的错，心累
