### ISSUE TITLE
美团券API

### ISSUE THREAD

**Issue by duchao1990** [HanSon/meituan-sdk#7]
请问里边有没有美团券API,

**Comment by Hanson** [comment]
发 API 链接，没有可以加

**Comment by duchao1990** [comment]
1. 已验券码查询 
http://api.open.cater.meituan.com/tuangou/coupon/queryById 
业务参数:couponCode

参数 | 类型 | 名称 | 是否必须 | 参数类型 | 最大长度
-- | -- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数 |  
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数 |  
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数 |  
version | int | 接口版本【默认是1】 | 非必须 | 系统级参数 |  
sign | string | 请求的数字签名 | 必须 | 系统级参数 |  
couponCode | string | 券码 | 必须 | 业务级参数 | 12位纯数字



2. 验券准备POST
http://api.open.cater.meituan.com/tuangou/coupon/prepare

参数 | 类型 | 名称 | 是否必须 | 参数类型 | 最大长度
-- | -- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数 |  
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数 |  
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数 |  
version | int | 接口版本【默认是1】 | 非必须 | 系统级参数 |  
sign | string | 请求的数字签名 | 必须 | 系统级参数 |  
couponCode | string | 券码 | 必须 | 业务级参数 | 12位纯数字



3. 执行验卷
http://api.open.cater.meituan.com/tuangou/coupon/consume

参数 | 类型 | 名称 | 是否必须 | 参数类型 | 最大长度
-- | -- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数 |  
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数 |  
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数 |  
version | int | 接口版本【默认是1】 | 非必须 | 系统级参数 |  
sign | string | 请求的数字签名 | 必须 | 系统级参数 |  
couponCode | string | 券码 | 必须 | 业务级参数 | 12位纯数字
count | int | 数量 | 必须 | 业务级参数 | 小于100的整数
eId | string | 商家登录ERP帐号ID | 必须 | 业务级参数 | 32位字符串
eName | string | 商家登录ERP帐号名称 | 必须 | 业务级参数 | 32位字符串
eOrderId | string | 第三方ERP订单号 | 必须 | 业务级参数 | 32位字符串


4.撤销验券
http://api.open.cater.meituan.com/tuangou/coupon/cancel

参数 | 类型 | 名称 | 是否必须 | 参数类型 | 最大长度
-- | -- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数 |  
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数 |  
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数 |  
version | int | 接口版本【默认是1】 | 非必须 | 系统级参数 |  
sign | string | 请求的数字签名 | 必须 | 系统级参数 |  
couponCode | string | 券码 | 必须 | 业务级参数 | 12位纯数字
type | type | 操作分类 | 必须 | 业务级参数 | type值永远为1撤销验券
eId | string | 商家登录ERP帐号ID | 必须 | 业务级参数 | 32位字符串
eName | string | 商家登录ERP帐号名称 | 必须 | 业务级参数 | 32位字符串

5.门店验券历史
http://api.open.cater.meituan.com/tuangou/coupon/queryListByDate

参数 | 类型 | 名称 | 是否必须 | 参数类型 | 最大长度
-- | -- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数 |  
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数 |  
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数 |  
version | int | 接口版本【默认是1】 | 非必须 | 系统级参数 |  
sign | string | 请求的数字签名 | 必须 | 系统级参数 |  
date | string | 日期 | 必须 | 业务级参数 | 2016-08-12
offset | int | 查询起始位置 | 必须 | 业务级参数 | 0
limit | int | 查询条数 | 必须 | 业务级参数 | 10

6.门店本地验券历史
http://api.open.cater.meituan.com/tuangou/coupon/queryLocalListByDate

参数 | 类型 | 名称 | 是否必须 | 参数类型 | 最大长度
-- | -- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数 |  
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数 |  
version | int | 接口版本【默认是1】 | 非必须 | 系统级参数 |  
sign | string | 请求的数字签名 | 必须 | 系统级参数 |  
date | string | 日期 | 必须 | 业务级参数 | 2016-08-12
offset | int | 查询起始位置 | 必须 | 业务级参数 | 0
limit | int | 查询条数 | 必须 | 业务级参数 | 10


7.门店套餐映射接口说明
http://api.open.cater.meituan.com/tuangou/coupon/querySetMealList

参数 | 类型 | 名称 | 是否必须 | 参数类型
-- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数
timestamp | int | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数
sign | string | 请求的数字签名 | 必须 | 系统级参数
dealStatus | int | 套餐状态 | 非必须 | 业务级参数，默认为1


8.查询团购订单结算明细
http://api.open.cater.meituan.com/tuangou/coupon/queryTradeDetail

参数 | 类型 | 名称 | 是否必须 | 备注
-- | -- | -- | -- | --
appAuthToken | string | 认领门店返回的token【一店一token】 | 必须 | 系统级参数
charset | string | 交互数据的编码【建议UTF-8】 | 必须 | 系统级参数
timestamp | long | 当前请求的时间戳【单位是秒】 | 必须 | 系统级参数
sign | string | 请求的数字签名 | 必须 | 系统级参数
couponCode | string | 团购券码 | 必须 | 业务级参数

**Comment by Hanson** [comment]
@duchao1990 OK，我加一下

**Comment by Hanson** [comment]
@duchao1990 已增加

可看 https://github.com/HanSon/meituan-sdk/commit/6eca29bb9ee448a1d1a89837a1d3af72e40bfa3b
