### ISSUE TITLE
调用餐饮开放平台UISDK时，需将signkey变为sign

### ISSUE THREAD

**Issue by ghost** [HanSon/meituan-sdk#9]
### 美团开发平台
> 尊敬的厂商，您好。
> 
> 为了更好地保护厂商的信息安全，厂商在调用餐饮开放平台UISDK时，需将signkey变为sign。美团·点评餐饮开放平台将于将于2019年2月26日下线通过signkey方式访问UISDK的能力，请您务必在此日期前完成对接。
> 
> 同时，请将具体开始改造时间和上线时间回复运营同学，如已使用sign方式调用UISDK，则可忽略此消息。针对届时未能完成对接且未给出合理理由的厂商，平台将暂停该开发者门店新增权限。
> 
> 文档如下：
> 
> 1、sign生成场景
> 
> 请参考：https://developer.meituan.com/openapi#3.2
> 
> 2、UISDK场景
> 
> ①授权，请参考： https://developer.meituan.com/openapi#4.1.2
> 
> ②解除授权，请参考：https://developer.meituan.com/openapi#4.3
> 
> ③菜品映射，请参考：https://developer.meituan.com/openapi#7.2.3
> 
> ④验券及查看订单，请参考：https://developer.meituan.com/openapi#2.4
> 
> ⑤闪惠及查看订单，请参考：https://developer.meituan.com/openapi#2.4
> 
> 注：对于UISDK加密的sign，不需要传递charset参数，且timestamp的单位是毫秒。
>

**Comment by Hanson** [comment]
fix https://github.com/Hanson/meituan-sdk/pull/10
